title: Gabriel González Medina
description: Your Site Description
baseurl: "/gabriel-gonzalez-medina"  # Add this - must match your repository name
url: "https://gagonzalezm.github.io"  # Add this - your GitHub Pages URL

# Hyde specific settings
remote_theme: poole/hyde  # Add this to use Hyde theme
sidebar-about-description: "Your sidebar description"
sidebar_nav_version: 2

# Hyde theme colors
theme-color: "#202020"

# Other common Hyde settings
permalink: pretty
paginate: 5

# Navigation
navigation:
  - title: "Home"
    url: /
  - title: "CV"
    url: /cv/
  - title: "Research"
    url: /research/
  - title: "Projects"
    url: /projects/
  - title: "GitHub"
    url: /github/
  - title: "Contact"
    url: /contact/
